### ISSUE TITLE
Bid Number is overriding - Is this valid?

### ISSUE THREAD

**Issue by rameshthoomu** [ITPeople-Blockchain/auction#29]
Pre-condition: Launched Peer and chaincode
Issue: Bid numbers are overriding. 
Steps to Reproduce:
Run Below commands as is:
1. ./PostUsers
2. ./PostItems
3. ./PostAuctionRequest
4. ./OpenAuctionRequestForBids
5. ./SubmitBids
6. Modify bid price (say 12000 for the last record) again run the ./SubmitBids command

Expected: Application should restrict user not to submit bids with new amount on old bid numbers.

**Comment by movee2016** [comment]
Bid number should be a unique number generated by the Client -- so right now it is not fixed.

**Comment by rameshthoomu** [comment]
Closing this issue
