### ISSUE TITLE
GetListOfItemsOnAuc - Function name is misleading

### ISSUE THREAD

**Issue by rameshthoomu** [ITPeople-Blockchain/auction#30]
`GetListOfItemsOnAuc` - Function name is misleading.

**Pre-Condition:** Launch Peer and Chaincode
**Description:** 
1. Register Users and Items
2. Execute  ./OpenAuctionRequestForBids and ./PostAuctionRequest
3. Execute
`$PEER chaincode query -l golang -n mycc -c '{"Function": "GetListOfItemsOnAuc", "Args": ["2016"]}'`
No records displayed after execute the above query. But, we should get list of items available on auction.

**Comment by movee2016** [comment]
Reanmed function to GetListofInitAucs but any other name suggested can be used

**Comment by rameshthoomu** [comment]
Working as expected
![30](https://cloud.githubusercontent.com/assets/17034502/16657152/67aaf6dc-442f-11e6-9dac-8b56bf256e87.PNG)
