### ISSUE TITLE
Current OwnerID is not changing in GetListOfItemsOnAuc after Transfer an item

### ISSUE THREAD

**Issue by rameshthoomu** [ITPeople-Blockchain/auction#33]
**Issue Descripton:**
Current OwnerID is not changing in `GetListOfItemsOnAuc` function after Transfer an Item.
**Pre-Condition:** 
Launch Peer and chaincode
**Steps to reproduce:**
Run below commands:
1. ./PostUsers
2. ./PostItems
3. ./PostAuctionRequest
4. ./TransferItem (Update the script with transferring ownership to other user). Execute below command to know the list of Item details on Auction request
`$PEER chaincode query -l golang -n mycc -c '{"Function": "GetListOfItemsOnAuc", "Args": ["2016"]}'`
and execute `$PEER chaincode query -l golang -n mycc -c '{"Function": "GetItem", "Args": ["1000"]}'` (edit the script with owner ID)

**Actual Result:**

![ownerid](https://cloud.githubusercontent.com/assets/17034502/16440721/8b3d55ac-3d92-11e6-986c-d4a31faaa614.PNG)
![capture](https://cloud.githubusercontent.com/assets/17034502/16440733/9cfd5396-3d92-11e6-9357-6dc33effcd72.PNG)

**Comment by movee2016** [comment]
Fixed in v21 - No Transfer if Item is on Auction

**Comment by rameshthoomu** [comment]
Fixed in V21.. Closing this.
![33](https://cloud.githubusercontent.com/assets/17034502/16641091/4d071fc2-43cb-11e6-9e1f-aca8fc15aee6.PNG)
