### ISSUE TITLE
Bidding is happening on Auction ID but not checking the Auction Item

### ISSUE THREAD

**Issue by rameshthoomu** [ITPeople-Blockchain/auction#34]
Open an Auction with Auction ID 1111 and Item 1000.. Submit bid with Auction ID 1111 and item 1900.. I could see Bid is successful on Item 1900 which is not on Auction.

**Comment by movee2016** [comment]
Fixed - Item on Bid is validated against item on Auction

**Comment by rameshthoomu** [comment]
Issue got fixed in the latest version. 
![34](https://cloud.githubusercontent.com/assets/17034502/16631412/05a66bb2-438d-11e6-9793-0aa1ac0fe08a.PNG)
