### ISSUE TITLE
Split chaincode in multiple files

### ISSUE THREAD

**Issue by sibelius** [ITPeople-Blockchain/auction#71]
This code is really good thanks.

we can make it more readable spliting the code in multiples files, like this repo: https://github.com/IBM-Blockchain/fabric-boilerplate/tree/master/src/build-chaincode

**Comment by Itpeoplecorp** [comment]
@sibelius thanks for your inputs. Yes we are syncing auction code with fabric v1.0 latest changes.

**Comment by ratnakar-asara** [comment]
@movee2016 has already worked on it and now we have itpUtils lib with helper methods
