### ISSUE TITLE
Which version for fabric ?

### ISSUE THREAD

**Issue by roamerxv** [ITPeople-Blockchain/auction#80]
The branch:master  supports the x86_64-1.0.0-snapshot-8d3275f for hyperledge/fabric ?

**Comment by rameshthoomu** [comment]
@roamerxv : Auction master branch is working as expected on fabric commit# 5b59e0.

**Comment by ratnakar-asara** [comment]
@roamerxv Yes it does work on the commit level **8d3275f**. Verified on this commit level and it works.
