### ISSUE TITLE
Membership Service Provider (MSP)  Manager cannot get msp for chain

### ISSUE THREAD

**Issue by AER-IoT** [ITPeople-Blockchain/auction#81]
Hi,

I try to use the auction example below :
https://github.com/ITPeople-Blockchain/auction
I successfully launch the ordere peer, but the Membership Service Provider (MSP) manager cannot find the msp of the chain.
Some of you already encountered this issue ?

ls -l $CORE_PEER_MSPCONFIGPATH
=>
drwxrwxr-x. ...  admincerts
drwxrwxr-x. ...  cacerts
drwxrwxr-x. ...  keystore
drwxrwxr-x. ...  signcerts

###Terminal 1 : ./orderer => OK
###Terminal 2 : peer node start -o 127.0.0.1:7050 => OK
###Terminal 3 => KO
peer chaincode invoke 127.0.0.1:7050 -n mycc -c '{"Args":["iPostUser","100", "USER", "Ashley Hart", "TRD", "Morrisville Parkway,
#216
, Morrisville, NC 27560", "9198063535", "ashley@itpeople.com", "SUNTRUST", "0001732345", "0234678", "2017-01-02 15:04:05"]}'
=> ...
2017-04-19 14:59:04.077 CEST [msp] Setup -> INFO 015 MSP manager setup complete, setup 1 msps
Error: Error endorsing chaincode: rpc error: code = 2 desc = could not get msp for chain [testchainid]

**Comment by ratnakar-asara** [comment]
@AER-IoT As per the documentation It works on the commit level **5b59e0652f9edf5bd12a6ff7fd2e9991495190fe** . Unabe to reprodcue the error.

can you confirm the following ?
* Did you first installed and Instantiated the chaincode ?
* when you provide the orderer endpoint you should give `-o` option as well. I don't see the same.Can you try with the below 

```
peer chaincode invoke -o 127.0.0.1:7050 -n mycc -c  '{"Args":["iPostUser","100", "USER", "Ashley Hart", "TRD",  "Morrisville Parkway, #216, Morrisville, NC 27560", "9198063535", "ashley@itpeople.com", "SUNTRUST", "0001732345", "0234678", "2017-01-02 15:04:05"]}'
```

**Comment by ratnakar-asara** [comment]
@AER-IoT Closing the issue for now, please re-open if you see the issue again.
